ENV[''SPACESHIP_SKIP_2FA_UPGRADE"] = "1"
default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Ad-Hoc Build for Firebase"
  lane :adhoc do
    match
  end
  desc "Distribute Build for Firebase"
  lane :distribute do
    firebase_app_distribution(
              app: "1:746497061570:ios:5fb46ace6328d54da8415b",
              ipa_path: "/tmp/circleci-artifacts/ipa/AdTag.ipa"
          )
  end
end
